require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
    pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
    pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
    pod 'CapacitorCommunitySqlite', :path => '../../node_modules/@capacitor-community/sqlite'
    pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
    pod 'CapacitorClipboard', :path => '../../node_modules/@capacitor/clipboard'
    pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
    pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
    pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
    pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
    pod 'CapacitorToast', :path => '../../node_modules/@capacitor/toast'
    pod 'CapgoCapacitorNavigationBar', :path => '../../node_modules/@capgo/capacitor-navigation-bar'
    pod 'CapacitorNativeSettings', :path => '../../node_modules/capacitor-native-settings'
    pod 'CapacitorNodejs', :path => '../../node_modules/capacitor-nodejs'
    pod 'Alamofire'
    pod 'SwiftSoup'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
