name: Node.js Deploy with SSH

on:
  push:
    branches:
      - gui

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }} # Specify your SSH port if it's not the default (22)
          script: |
            # SSH into the server
            cd studentcomp

            # Stop previous application if running
            pm2 stop studentcompaniongui || true

            # Pull the latest changes
            git pull origin gui

            # Install or update dependencies
            npm install

            # Start the Node.js application with a process manager like PM2
            pm2 start index.js --name studentcompaniongui
